### ISSUE TITLE
Legal disclaimer for use of django-consent

### ISSUE THREAD

**Issue by emilkjer** [django-denmark/django-consent#6]
Implement a legal disclaimer in the documentation stating that the use of the software is at the users own risk and advice given in the documentation or software is not legally valid. If the user would like to be compliant they should seek advice by a lawyer.

**Comment by benjaoming** [comment]
Adding a disclaimer in the README for now, docs are still pending. Note that the GPL also states this in the LICENSE file:

>    This program is distributed in the hope that it will be useful,
>    but WITHOUT ANY WARRANTY; without even the implied warranty of
>    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>    GNU General Public License for more details.
